export const cardsData = [
    {
        id: 1,
        title: "Card 1",
        datatime: "24/03/2022 16:12 hs.",
        creator: "Facundo",
        description: "lorem ipsum dolor sit",
        type: "new",
        priority: "high",
    },
    {
        id: 2,
        title: "Card 2",
        datatime: "24/03/2022 16:12 hs.",
        creator: "Facundo",
        description: "lorem ipsum dolor sit",
        type: "new",
        priority: "high",
    },
    {
        id: 3,
        title: "Card 3",
        datatime: "24/03/2022 16:12 hs.",
        creator: "Facundo",
        description: "lorem ipsum dolor sit",
        type: "new",
        priority: "high",
    },
    {
        id: 4,
        title: "Card 4",
        datatime: "24/03/2022 16:12 hs.",
        creator: "Facundo",
        description: "lorem ipsum dolor sit",
        type: "new",
        priority: "high",
    },
]    